const http=require('http'),fs=require('fs'),path=require('path');
const PORT=process.env.PORT||3000, DATA=process.env.DATA_FILE||path.join(__dirname,'data','db.json');
function fresh(){return {workers:[{id:'W001',name:'Amit Technician',mobile:'9999990001',status:'Available',lat:null,lng:null,lastLocation:null}],olts:[{id:'OLT001',name:'Main OLT',location:'Main Office'}],pons:[{id:'PON001',oltId:'OLT001',name:'PON 1'}],customers:[{id:'RB1001',name:'Demo Customer',mobile:'9999999999',address:'Narnaul',pppoe:'demo1001',oltId:'OLT001',ponId:'PON001',plan:'30 Mbps',price:499,startDate:'2026-09-23',expiry:'2026-10-23',status:'Active',password:'1234',credit:0,dueBalance:0,dueItems:[]},{id:'RB1002',name:'Rahul Kumar',mobile:'9999999998',address:'Neemrana',pppoe:'rahul1002',oltId:'OLT001',ponId:'PON001',plan:'50 Mbps',price:599,startDate:'2026-09-12',expiry:'2026-10-12',status:'Due Soon',password:'1234',credit:0,dueBalance:0,dueItems:[]}],plans:[{name:'30 Mbps',price:499},{name:'50 Mbps',price:599},{name:'100 Mbps',price:899}],offers:{},notifications:[],payments:[],complaints:[],referrals:[],upgrades:[],passwordChangeRequests:[],settings:{upi:'8675938000@axl'}}}
function readDB(){try{const d=JSON.parse(fs.readFileSync(DATA,'utf8'));const f=fresh();return Object.assign(f,d,{olts:d.olts||f.olts,pons:d.pons||f.pons,customers:(d.customers||f.customers).map(c=>Object.assign({oltId:'OLT001',ponId:(d.pons&&d.pons[0]?d.pons[0].id:'PON001'),dueBalance:0,dueItems:[],passwordChangeCount:0,passwordChangeAllowed:false},c)),plans:d.plans||f.plans,offers:d.offers||{},notifications:d.notifications||[],payments:d.payments||[],complaints:d.complaints||[],referrals:d.referrals||[],upgrades:d.upgrades||[],passwordChangeRequests:d.passwordChangeRequests||[],workers:d.workers||f.workers,settings:Object.assign(f.settings,d.settings||{})})}catch(e){const d=fresh();writeDB(d);return d}}
function writeDB(d){fs.writeFileSync(DATA,JSON.stringify(d,null,2))}
function addMonths(date,n){const d=new Date(date.getFullYear(),date.getMonth(),date.getDate()),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()+n);const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();d.setDate(Math.min(day,last));return d}
function iso(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return y+'-'+m+'-'+day}
function send(res,status,data,type='application/json'){res.writeHead(status,{'Content-Type':type,'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type'});res.end(type==='application/json'?JSON.stringify(data):data)}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}})})}
function idOK(id){return /^RB\d+$/.test(String(id||'').trim().toUpperCase())}
function addNotification(d,to,title,message,meta={}){d.notifications=d.notifications||[];d.notifications.push({id:'NT'+Date.now()+Math.floor(Math.random()*1000),to:String(to||'ALL'),title:String(title||'Rao Brothers'),message:String(message||''),date:new Date().toLocaleString('en-IN'),createdAt:new Date().toISOString(),...meta});if(d.notifications.length>500)d.notifications=d.notifications.slice(-500)}

function runExpiryReminders(){
 try{
  const d=readDB(), now=new Date();
  const hour=now.getHours();
  if(hour!==9 && hour!==19) return;
  const today=new Date(now.getFullYear(),now.getMonth(),now.getDate());
  let changed=false;
  for(const c of d.customers||[]){
   if(!c.expiry || !/^\d{4}-\d{2}-\d{2}$/.test(c.expiry)) continue;
   const ex=new Date(c.expiry+'T00:00:00');
   const days=Math.round((ex-today)/86400000);
   if(days<0 || days>5) continue;
   const key=`EXPIRY:${c.id}:${c.expiry}:${days}:${hour}`;
   if((d.notifications||[]).some(n=>n.metaKey===key)) continue;
   const msg=days===0
    ? `⚠️ Aaj aapka plan expire ho raha hai. Due amount ₹${Number(c.dueBalance||0).toFixed(2)}. Please recharge karein.`
    : `🔔 Aapka ${c.plan||'Internet'} plan ${days} din baad (${c.expiry}) khatam hone wala hai. Please recharge karein. Due amount ₹${Number(c.dueBalance||0).toFixed(2)}.`;
   addNotification(d,c.id,'📅 Plan Expiry Reminder',msg,{metaKey:key});
   changed=true;
  }
  if(changed) writeDB(d);
 }catch(e){console.error('expiry reminder error',e.message)}
}
setInterval(runExpiryReminders,60000);
const server=http.createServer(async(req,res)=>{
if(req.url.split('?')[0]==='/admin2'){try{const html=fs.readFileSync(path.join(__dirname,'public','admin2.html'),'utf8');return send(res,200,html,'text/html')}catch(e){return send(res,500,'Admin2 file missing','text/plain')}}if(req.method==='OPTIONS')return send(res,204,'');const u=new URL(req.url,'http://localhost');try{const d=readDB();
if(u.pathname==='/api/health')return send(res,200,{ok:true,service:'Rao Brothers',time:new Date().toISOString()});
if(u.pathname==='/api/settings'&&req.method==='GET')return send(res,200,d.settings);
if(u.pathname==='/api/settings'&&req.method==='POST'){const x=await body(req);d.settings=Object.assign({},d.settings||{}, {upi:String(x.upi||'').trim()});writeDB(d);return send(res,200,d.settings); }
if(u.pathname==='/api/customers'&&req.method==='GET'){const cid=String(u.searchParams.get('customerId')||'').trim().toUpperCase();const list=cid?d.customers.filter(c=>c.id===cid):d.customers;return send(res,200,list.map(({password,...x})=>x));}
if(u.pathname==='/api/olts'&&req.method==='GET')return send(res,200,d.olts);
if(u.pathname==='/api/pons'&&req.method==='GET')return send(res,200,d.pons);
if(u.pathname==='/api/pon'&&req.method==='POST'){const x=await body(req),oltId=String(x.oltId||'').trim().toUpperCase(),name=String(x.name||'').trim();if(!d.olts.some(o=>o.id===oltId))return send(res,400,{error:'Valid OLT required'});if(!name)return send(res,400,{error:'PON name required'});let n=d.pons.reduce((m,o)=>Math.max(m,Number(String(o.id).replace(/\D/g,''))||0),0)+1;const pon={id:'PON'+String(n).padStart(3,'0'),oltId,name};d.pons.push(pon);writeDB(d);return send(res,200,pon)}
if(u.pathname==='/api/pon'&&req.method==='PUT'){const x=await body(req),id=String(x.id||'').trim().toUpperCase(),oltId=String(x.oltId||'').trim().toUpperCase(),name=String(x.name||'').trim(),p=d.pons.find(a=>a.id===id);if(!p)return send(res,404,{error:'PON not found'});if(!d.olts.some(o=>o.id===oltId))return send(res,400,{error:'Valid OLT required'});if(!name)return send(res,400,{error:'PON name required'});p.oltId=oltId;p.name=name;d.customers.filter(c=>c.ponId===id).forEach(c=>c.oltId=oltId);writeDB(d);return send(res,200,p)}
if(u.pathname==='/api/pon'&&req.method==='DELETE'){const id=String(u.searchParams.get('ponId')||'').trim().toUpperCase();if(!id)return send(res,400,{error:'PON ID required'});if(d.customers.some(c=>c.ponId===id))return send(res,400,{error:'PON has customers. Move customers first.'});d.pons=d.pons.filter(p=>p.id!==id);writeDB(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/olt'&&req.method==='POST'){const x=await body(req),name=String(x.name||'').trim(),location=String(x.location||'').trim();if(!name)return send(res,400,{error:'OLT name required'});let n=d.olts.reduce((m,o)=>Math.max(m,Number(String(o.id).replace(/\D/g,''))||0),0)+1;const o={id:'OLT'+String(n).padStart(3,'0'),name,location};d.olts.push(o);writeDB(d);return send(res,200,o)}
if(u.pathname==='/api/olt'&&req.method==='DELETE'){const id=String(u.searchParams.get('oltId')||'').toUpperCase();if(!id)return send(res,400,{error:'OLT ID required'});if(d.customers.some(c=>c.oltId===id))return send(res,400,{error:'OLT has customers. Reassign customers first.'});d.olts=d.olts.filter(o=>o.id!==id);writeDB(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/customer/password'&&req.method==='GET'){const id=String(u.searchParams.get('customerId')||'').trim().toUpperCase(),c=d.customers.find(a=>a.id===id);if(!c)return send(res,404,{error:'Customer not found'});return send(res,200,{customerId:c.id,password:String(c.password||''),passwordChangeCount:Number(c.passwordChangeCount||0),passwordChangeAllowed:!!c.passwordChangeAllowed})}
if(u.pathname==='/api/customer/password/change'&&req.method==='POST'){const x=await body(req),id=String(x.customerId||'').trim().toUpperCase(),c=d.customers.find(a=>a.id===id);if(!c)return send(res,404,{error:'Customer not found'});const old=String(x.currentPassword||''),nw=String(x.newPassword||'');if(!nw||nw.length<4)return send(res,400,{error:'New password must be at least 4 characters'});if(String(c.password||'')!==old)return send(res,401,{error:'Current password is incorrect'});const count=Number(c.passwordChangeCount||0);if(count>=1&&!c.passwordChangeAllowed){d.passwordChangeRequests=d.passwordChangeRequests||[];let q=d.passwordChangeRequests.find(r=>r.customerId===id&&r.status==='Pending');if(!q){q={id:'PCR'+Date.now(),customerId:id,customerName:c.name,status:'Pending',requestedAt:new Date().toISOString()};d.passwordChangeRequests.push(q);addNotification(d,'ADMIN','🔐 Password Change Request',`${c.name} (${id}) requested another customer-app password change.`);writeDB(d)}return send(res,200,{ok:false,requestRequired:true,message:'Password change request sent to Admin.'})}c.password=nw;c.passwordChangeCount=count+1;c.passwordChangeAllowed=false;writeDB(d);return send(res,200,{ok:true,message:'Password changed successfully.'})}
if(u.pathname==='/api/password-requests'&&req.method==='GET')return send(res,200,(d.passwordChangeRequests||[]).slice().reverse());
if(u.pathname==='/api/password-request/approve'&&req.method==='POST'){const x=await body(req),q=(d.passwordChangeRequests||[]).find(r=>r.id===String(x.id||''));if(!q)return send(res,404,{error:'Request not found'});const c=d.customers.find(a=>a.id===q.customerId);if(!c)return send(res,404,{error:'Customer not found'});q.status='Approved';q.approvedAt=new Date().toISOString();c.passwordChangeAllowed=true;addNotification(d,c.id,'🔐 Password Change Approved','Admin has approved your password change request. You can change your app password one more time.');writeDB(d);return send(res,200,q)}
if(u.pathname==='/api/password-request/reject'&&req.method==='POST'){const x=await body(req),q=(d.passwordChangeRequests||[]).find(r=>r.id===String(x.id||''));if(!q)return send(res,404,{error:'Request not found'});q.status='Rejected';q.rejectedAt=new Date().toISOString();writeDB(d);return send(res,200,q)}
if(u.pathname==='/api/login'&&req.method==='POST'){const x=await body(req),id=String(x.id||'').trim().toUpperCase(),u1=d.customers.find(c=>c.id===id&&c.password===String(x.password||''));if(!u1)return send(res,401,{error:'Invalid Customer ID or Password'});const {password,...safe}=u1;return send(res,200,safe)}
if(u.pathname==='/api/customer/existing'&&req.method==='POST'){
 const x=await body(req); const cleanId=String(x.id||'').trim().toUpperCase();
 if(!String(x.name||'').trim()||!String(x.mobile||'').trim()||!String(x.pppoe||'').trim())return send(res,400,{error:'Name, mobile and PPPoE username required'});
 if(cleanId && !/^RB\d+$/.test(cleanId))return send(res,400,{error:'Customer ID must look like RB1001'});
 if(cleanId && d.customers.some(c=>c.id===cleanId))return send(res,400,{error:'Customer ID already exists'});
 if(d.customers.some(c=>String(c.pppoe||'').toLowerCase()===String(x.pppoe).trim().toLowerCase()))return send(res,400,{error:'PPPoE username already exists'});
 const plan=d.plans.find(p=>p.name===x.plan)||d.plans[0];
 const price=Number(x.price!==undefined&&x.price!==''?x.price:plan.price); if(!Number.isFinite(price)||price<0)return send(res,400,{error:'Valid bill amount required'});
 const start=String(x.startDate||'').trim(),expiry=String(x.expiry||'').trim();
 if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(expiry))return send(res,400,{error:'Valid start and expiry dates required'});
 const totalMonths=Math.max(1,Math.min(60,parseInt(x.totalMonths||1)||1)),usedMonths=Math.max(0,Math.min(60,parseInt(x.usedMonths||0)||0)),dueMonths=Math.max(0,Math.min(60,parseInt(x.dueMonths||0)||0));
 const dueAmount=Math.max(0,Number(x.dueAmount||0));
 const n=d.customers.length?Math.max(...d.customers.map(c=>Number(String(c.id).replace(/\D/g,''))||1000))+1:1001;
 const id=cleanId||'RB'+n; const oid=String(x.oltId||d.olts[0]?.id||'OLT001').toUpperCase(); if(!d.olts.some(o=>o.id===oid))return send(res,400,{error:'OLT not found'});
 const pid=String(x.ponId||d.pons.find(p=>p.oltId===oid)?.id||d.pons[0]?.id||'PON001').toUpperCase(); if(d.pons.length&&!d.pons.some(p=>p.id===pid))return send(res,400,{error:'PON not found'});
 const c={id,name:String(x.name).trim(),mobile:String(x.mobile).trim(),address:String(x.address||'').trim(),pppoe:String(x.pppoe).trim(),oltId:oid,ponId:pid,plan:plan.name,price,startDate:start,expiry,totalMonths,usedMonths,dueMonths,dueBalance:Number(dueAmount.toFixed(2)),dueItems:[],status:String(x.status||'Active'),password:String(x.password||'1234'),passwordChangeCount:0,passwordChangeAllowed:false,credit:0,existingCustomer:true,importedAt:new Date().toISOString()};
 if(c.dueBalance>0)c.dueItems.push({id:'LED'+Date.now(),type:'Existing Due',description:`Existing pending payment — ${dueMonths} month(s)`,amount:c.dueBalance,months:dueMonths,date:new Date().toISOString(),status:'Pending'});
 d.customers.push(c); if(c.dueBalance>0)addNotification(d,c.id,'🧾 Existing Customer Payment Due',`Pending payment ₹${c.dueBalance} for ${dueMonths} month(s). Your service is valid until ${c.expiry}.`); writeDB(d); const {password,...safe}=c; return send(res,200,safe);
}
if(u.pathname==='/api/customer'&&req.method==='POST'){const x=await body(req);if(!String(x.name||'').trim()||!String(x.mobile||'').trim())return send(res,400,{error:'Name and mobile required'});let n=d.customers.length?Math.max(...d.customers.map(c=>Number(String(c.id).replace(/\D/g,''))||1000))+1:1001;const now=new Date(),plan=d.plans.find(p=>p.name===x.plan)||d.plans[0],months=Math.max(1,Math.min(60,parseInt(x.months||1)||1)),startRaw=String(x.startDate||'').trim(),start=startRaw&&/^\d{4}-\d{2}-\d{2}$/.test(startRaw)?new Date(startRaw+'T00:00:00'):now;const c={id:'RB'+n,name:String(x.name).trim(),mobile:String(x.mobile).trim(),address:String(x.address||'').trim(),pppoe:String(x.pppoe||'').trim(),oltId:String(x.oltId||d.olts[0]?.id||'OLT001').toUpperCase(),ponId:String(x.ponId||d.pons.find(p=>p.oltId===String(x.oltId||d.olts[0]?.id||'OLT001').toUpperCase())?.id||d.pons[0]?.id||'PON001').toUpperCase(),plan:plan.name,price:Number(plan.price),months,startDate:iso(start),expiry:(/^\d{4}-\d{2}-\d{2}$/.test(String(x.expiry||''))?String(x.expiry):iso(addMonths(start,months))),status:'Active',password:String(x.password||'1234'),passwordChangeCount:0,passwordChangeAllowed:false,credit:0};d.customers.push(c);writeDB(d);const {password,...safe}=c;return send(res,200,safe)}
if(u.pathname==='/api/customer'&&req.method==='DELETE'){const id=String(u.searchParams.get('customerId')||'').trim().toUpperCase();const idx=d.customers.findIndex(c=>c.id===id);if(idx<0)return send(res,404,{error:'Customer not found'});if(d.complaints.some(c=>c.customerId===id&&c.status!=='Resolved'))return send(res,400,{error:'Customer has active complaints. Resolve them first.'});d.customers.splice(idx,1);delete d.offers[id];d.notifications=d.notifications.filter(n=>n.to!==id);writeDB(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/customer/activate'&&req.method==='POST'){const x=await body(req),id=String(x.id||'').trim().toUpperCase(),c=d.customers.find(a=>a.id===id);if(!c)return send(res,404,{error:'Customer not found'});const months=Math.max(1,Math.min(60,parseInt(x.months||1)||1)),start=String(x.startDate||iso(new Date())).trim();if(!/^\d{4}-\d{2}-\d{2}$/.test(start))return send(res,400,{error:'Invalid start date'});const base=new Date(start+'T00:00:00');if(Number.isNaN(base.getTime()))return send(res,400,{error:'Invalid start date'});c.startDate=start;c.expiry=iso(addMonths(base,months));c.status='Active';c.activatedAt=new Date().toISOString();addNotification(d,c.id,'✅ Connection Activated',`Your connection has been activated from ${start} until ${c.expiry}.`);writeDB(d);const {password,...safe}=c;return send(res,200,safe)}
if(u.pathname==='/api/customer'&&req.method==='PUT'){const x=await body(req),id=String(x.id||'').trim().toUpperCase(),c=d.customers.find(a=>a.id===id);if(!c)return send(res,404,{error:'Customer not found'});if(x.oltId){const oid=String(x.oltId).toUpperCase();if(!d.olts.some(o=>o.id===oid))return send(res,400,{error:'OLT not found'});c.oltId=oid}if(x.ponId){const pid=String(x.ponId).toUpperCase(),p=d.pons.find(a=>a.id===pid);if(!p)return send(res,400,{error:'PON not found'});c.ponId=pid;c.oltId=p.oltId}if(x.price!==undefined){const price=Number(x.price);if(!Number.isFinite(price)||price<0)return send(res,400,{error:'Valid bill amount required'});c.price=price}if(x.startDate!==undefined){const sd=String(x.startDate||'').trim();if(sd&&!/^\d{4}-\d{2}-\d{2}$/.test(sd))return send(res,400,{error:'Invalid start date'});c.startDate=sd}if(x.expiry!==undefined){const ed=String(x.expiry||'').trim();if(ed&&!/^\d{4}-\d{2}-\d{2}$/.test(ed))return send(res,400,{error:'Invalid expiry date'});c.expiry=ed}if(x.status!==undefined)c.status=String(x.status);const {password,...safe}=c;writeDB(d);return send(res,200,safe)}
if(u.pathname==='/api/offer'&&req.method==='GET'){const id=(u.searchParams.get('customerId')||'').trim().toUpperCase();return send(res,200,d.offers[id]&&d.offers[id].active!==false?d.offers[id]:null)}
if(u.pathname==='/api/offer'&&req.method==='POST'){const x=await body(req),id=String(x.customerId||'').trim().toUpperCase();if(!idOK(id))return send(res,400,{error:'Invalid customer ID'});const paid=Math.max(1,Math.min(24,parseInt(x.paidMonths||5)||5)),free=Math.max(0,Math.min(24,parseInt(x.freeMonths||1)||0)),now=new Date(),title=String(x.title||`PAY ${paid} MONTHS — GET ${free} MONTH FREE`).trim(),message=String(x.message||`Pay for ${paid} months and get ${free} month${free===1?'':'s'} free.`).trim();d.offers[id]={customerId:id,title,message,active:true,activatedAt:now.toISOString(),paidMonths:paid,freeMonths:free,paidUntil:iso(addMonths(now,paid)),serviceUntil:iso(addMonths(now,paid+free)),updatedAt:now.toISOString()};writeDB(d);return send(res,200,d.offers[id])}
if(u.pathname==='/api/offer'&&req.method==='DELETE'){const id=(u.searchParams.get('customerId')||'').trim().toUpperCase();if(d.offers[id])delete d.offers[id];writeDB(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/offers'&&req.method==='GET')return send(res,200,Object.values(d.offers).filter(x=>x.active!==false));
if(u.pathname==='/api/notifications'&&req.method==='GET'){const id=(u.searchParams.get('customerId')||'').trim().toUpperCase(),c=d.customers.find(a=>a.id===id);if(u.searchParams.get('admin')==='1')return send(res,200,d.notifications.slice(-50).reverse());return send(res,200,d.notifications.filter(n=>n.to==='ALL'||n.to===id||(c&&n.to==='OLT:'+c.oltId)||(c&&n.to==='PON:'+c.ponId)).slice(-30).reverse())}
if(u.pathname==='/api/notification'&&req.method==='POST'){const x=await body(req),n={id:'NT'+Date.now(),to:String(x.to||'ALL').toUpperCase(),title:String(x.title||'Rao Brothers Message'),message:String(x.message||''),date:new Date().toLocaleString('en-IN'),time:Date.now()};if(!n.message)return send(res,400,{error:'Message required'});d.notifications.push(n);writeDB(d);return send(res,200,n)}
if(u.pathname==='/api/notification'&&req.method==='DELETE'){const id=String(u.searchParams.get('id')||'').trim();const before=d.notifications.length;d.notifications=d.notifications.filter(n=>n.id!==id);if(d.notifications.length===before)return send(res,404,{error:'Notification not found'});writeDB(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/referral/new'&&req.method==='POST'){const x=await body(req),ref=String(x.referrerId||'').trim().toUpperCase();if(!idOK(ref)||!d.customers.some(c=>c.id===ref))return send(res,400,{error:'Valid referrer customer ID required'});if(!String(x.name||'').trim()||!String(x.mobile||'').trim())return send(res,400,{error:'New customer name and mobile required'});const r={id:'RF'+Date.now(),referrerId:ref,name:String(x.name).trim(),mobile:String(x.mobile).trim(),address:String(x.address||'').trim(),plan:String(x.plan||d.plans[0].name),status:'Pending',newCustomerDiscount:100,referrerCredit:100,createdAt:new Date().toISOString()};d.referrals.push(r);writeDB(d);return send(res,200,r)}
if(u.pathname==='/api/referrals'&&req.method==='GET')return send(res,200,d.referrals.slice().reverse());
if(u.pathname==='/api/referral/approve'&&req.method==='POST'){const x=await body(req),r=d.referrals.find(a=>a.id===x.id);if(!r)return send(res,404,{error:'Referral not found'});if(r.status!=='Pending')return send(res,400,{error:'Referral already processed'});let n=Math.max(...d.customers.map(c=>Number(String(c.id).replace(/\D/g,''))||1000))+1,plan=d.plans.find(p=>p.name===r.plan)||d.plans[0],now=new Date();const c={id:'RB'+n,name:r.name,mobile:r.mobile,address:r.address,pppoe:'',plan:plan.name,price:Number(plan.price),startDate:iso(now),expiry:iso(addMonths(now,1)),status:'Active',password:'1234',credit:100};d.customers.push(c);const ref=d.customers.find(a=>a.id===r.referrerId);if(ref)ref.credit=Number(ref.credit||0)+100;r.status='Approved';r.approvedAt=now.toISOString();r.newCustomerId=c.id;writeDB(d);return send(res,200,{referral:r,customer:{id:c.id,name:c.name,mobile:c.mobile,plan:c.plan,discount:100},referrerCredit:ref?ref.credit:0})}
if(u.pathname==='/api/referral'&&req.method==='DELETE'){const id=String(u.searchParams.get('id')||'').trim();const before=d.referrals.length;d.referrals=d.referrals.filter(r=>r.id!==id);if(d.referrals.length===before)return send(res,404,{error:'Referral not found'});writeDB(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/referral/reject'&&req.method==='POST'){const x=await body(req),r=d.referrals.find(a=>a.id===x.id);if(!r)return send(res,404,{error:'Referral not found'});r.status='Rejected';r.rejectedAt=new Date().toISOString();writeDB(d);return send(res,200,r)}
if(u.pathname==='/api/referral/credit'&&req.method==='GET'){const id=(u.searchParams.get('customerId')||'').trim().toUpperCase(),c=d.customers.find(a=>a.id===id);return send(res,200,{customerId:id,credit:c?Number(c.credit||0):0})}
if(u.pathname==='/api/ledger'&&req.method==='GET'){
 const id=String(u.searchParams.get('customerId')||'').trim().toUpperCase();
 if(id){const c=d.customers.find(a=>a.id===id);if(!c)return send(res,404,{error:'Customer not found'});return send(res,200,{customerId:id,dueBalance:Number(c.dueBalance||0),dueItems:c.dueItems||[]});}
 return send(res,200,d.customers.map(c=>({customerId:c.id,name:c.name,dueBalance:Number(c.dueBalance||0),dueItems:c.dueItems||[]})).filter(x=>x.dueBalance>0));
}
if(u.pathname==='/api/admin/service-credit'&&req.method==='POST'){
 const x=await body(req),id=String(x.customerId||'').trim().toUpperCase(),c=d.customers.find(a=>a.id===id);
 if(!c)return send(res,404,{error:'Customer not found'});
 const months=Math.max(1,Math.min(60,parseInt(x.months||1)||1)),price=Number(x.amount||Number(c.price||0)*months),mode=String(x.mode||'credit').toLowerCase()==='cash'?'Cash':'Udhaar';
 if(!Number.isFinite(price)||price<0)return send(res,400,{error:'Invalid amount'});
 const today=new Date(),oldExpiry=c.expiry&&/^\\d{4}-\\d{2}-\\d{2}$/.test(c.expiry)?new Date(c.expiry+'T00:00:00'):today;
 const base=(oldExpiry>today&&c.status==='Active')?oldExpiry:today;
 const newExpiry=iso(addMonths(base,months));
 c.startDate=c.startDate||iso(today);c.expiry=newExpiry;c.status='Active';c.months=months;
 const item={id:'LED'+Date.now(),type:mode,description:String(x.description||('Service recharge '+months+' month(s)')),amount:price,months,date:new Date().toISOString(),status:mode==='Cash'?'Paid':'Pending'};
 c.dueItems=c.dueItems||[];
 if(mode==='Udhaar'){c.dueBalance=Number(c.dueBalance||0)+price;c.dueItems.push(item);addNotification(d,c.id,'🧾 Recharge on Credit / Udhaar',`Your ${months} month recharge is active until ${c.expiry}. Pending payment: ₹${c.dueBalance}.`);}
 else {item.status='Paid';c.dueItems.push(item);addNotification(d,c.id,'💵 Cash Payment Recorded',`Cash payment of ₹${price} recorded. Your plan is active until ${c.expiry}.`);}
 writeDB(d);return send(res,200,{customer:c,item});
}
if(u.pathname==='/api/admin/settle-due'&&req.method==='POST'){
 const x=await body(req),id=String(x.customerId||'').trim().toUpperCase(),c=d.customers.find(a=>a.id===id);if(!c)return send(res,404,{error:'Customer not found'});
 const pay=Math.max(0,Number(x.amount||0));if(!pay)return send(res,400,{error:'Valid cash amount required'});
 const due=Number(c.dueBalance||0),used=Math.min(pay,due);c.dueBalance=Math.max(0,due-used);c.dueItems=c.dueItems||[];c.dueItems.push({id:'LED'+Date.now(),type:'Cash Settlement',description:String(x.description||'Cash settlement of pending dues'),amount:used,date:new Date().toISOString(),status:'Paid'});
 addNotification(d,c.id,'💵 Pending Due Paid',`Cash ₹${used} received. Remaining payment pending: ₹${c.dueBalance}.`);writeDB(d);return send(res,200,{customerId:id,paid:used,dueBalance:c.dueBalance});
}
if(u.pathname==='/api/admin/customer-charge'&&req.method==='POST'){
 const x=await body(req),id=String(x.customerId||'').trim().toUpperCase(),c=d.customers.find(a=>a.id===id);
 if(!c)return send(res,404,{error:'Customer not found'});
 const amount=Number(x.amount||0),desc=String(x.description||'Customer charge').trim();
 if(!Number.isFinite(amount)||amount<=0)return send(res,400,{error:'Valid charge amount required'});
 if(!desc)return send(res,400,{error:'Charge reason required'});
 c.dueBalance=Number(c.dueBalance||0)+amount;c.dueItems=c.dueItems||[];
 c.dueItems.push({id:'CHG'+Date.now()+id,type:'Customer Charge',description:desc,amount:Number(amount.toFixed(2)),date:new Date().toISOString(),status:'Pending'});
 addNotification(d,c.id,'💸 New Charge Added',`${desc}: ₹${Number(amount.toFixed(2))} has been added to your pending account balance.`);
 writeDB(d);return send(res,200,{customerId:id,name:c.name,amount:Number(amount.toFixed(2)),dueBalance:Number(c.dueBalance||0)});
}
if(u.pathname==='/api/admin/common-expense'&&req.method==='POST'){
 const x=await body(req),desc=String(x.description||'Common expense').trim(),mode=String(x.mode||'split').toLowerCase(),total=Number(x.total||0),per=Number(x.perCustomer||0);
 const targets=d.customers.filter(c=>c.status!=='Deleted');if(!targets.length)return send(res,400,{error:'No customers'});
 if(mode==='same'){if(!Number.isFinite(per)||per<=0)return send(res,400,{error:'Enter per-customer amount'});}else{if(!Number.isFinite(total)||total<=0)return send(res,400,{error:'Enter total expense'});}
 const share=mode==='same'?per:total/targets.length;
 targets.forEach(c=>{c.dueBalance=Number(c.dueBalance||0)+share;c.dueItems=c.dueItems||[];c.dueItems.push({id:'EXP'+Date.now()+c.id,type:'Common Expense',description:desc,amount:Number(share.toFixed(2)),date:new Date().toISOString(),status:'Pending'});});
 addNotification(d,'ALL','🧾 Common Charge Added',`${desc}: ₹${Number(share.toFixed(2))} has been added to each customer account.`);writeDB(d);return send(res,200,{customersAffected:targets.length,perCustomer:Number(share.toFixed(2)),totalApplied:Number((share*targets.length).toFixed(2))});
}
if(u.pathname==='/api/payment'&&req.method==='POST'){
 const x=await body(req),customerId=String(x.customerId||'').toUpperCase(),c=d.customers.find(a=>a.id===customerId);
 if(!c)return send(res,404,{error:'Customer not found'});
 const amount=Number(x.amount||c.price||0),months=Math.max(1,Number(x.months||1));
 const utr=String(x.utr||'').trim(),payerName=String(x.payerName||c.name||'').trim(),proof=String(x.proofImage||'').trim();
 if(!utr&&!proof)return send(res,400,{error:'Please provide UTR OR payment screenshot.'});
 if(proof && proof.length>4000000)return send(res,400,{error:'Payment screenshot is too large. Please use a smaller image.'});
 const p={id:'PAY'+Date.now(),customerId,customerName:c.name,amount,months,status:'Pending',date:new Date().toISOString(),utr,payerName,proofImage:proof||null};
 d.payments.push(p);addNotification(d,'ADMIN','💳 New Payment Received',`${c.name} (${customerId}) submitted ₹${amount}. ${utr?'UTR: '+utr+'. ':''}${proof?'Payment screenshot attached. ':''}Please verify payment.`,{paymentId:p.id});writeDB(d);return send(res,200,p)
}
if(u.pathname==='/api/payment'&&req.method==='DELETE'){const id=String(u.searchParams.get('id')||'').trim();const before=d.payments.length;d.payments=d.payments.filter(p=>p.id!==id);if(d.payments.length===before)return send(res,404,{error:'Payment not found'});writeDB(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/payments'&&req.method==='GET')return send(res,200,d.payments.slice().reverse());
if(u.pathname==='/api/payment/reject'&&req.method==='POST'){const x=await body(req),p=d.payments.find(a=>a.id===x.id);if(!p)return send(res,404,{error:'Payment not found'});p.status='Rejected';writeDB(d);return send(res,200,p)}
if(u.pathname==='/api/payment/approve'&&req.method==='POST'){
 const x=await body(req),p=d.payments.find(a=>a.id===x.id);if(!p)return send(res,404,{error:'Payment not found'});
 if(p.status==='Approved')return send(res,200,p);
 p.status='Approved';p.approvedAt=new Date().toISOString();const c=d.customers.find(a=>a.id===p.customerId);
 if(c){const start=new Date(),credit=Math.min(Number(c.credit||0),Number(p.amount||0));c.credit=Math.max(0,Number(c.credit||0)-credit);c.startDate=iso(start);c.expiry=iso(addMonths(start,Math.max(1,p.months||1)));c.status='Active';addNotification(d,c.id,'✅ Payment Approved',`Your payment of ₹${p.amount} has been approved. Your plan is active until ${c.expiry}.`);}
 writeDB(d);return send(res,200,p)
}
if(u.pathname==='/api/workers'&&req.method==='GET')return send(res,200,d.workers);
if(u.pathname==='/api/worker'&&req.method==='POST'){const x=await body(req),name=String(x.name||'').trim(),mobile=String(x.mobile||'').trim();if(!name)return send(res,400,{error:'Technician name required'});let n=d.workers.reduce((m,w)=>Math.max(m,Number(String(w.id).replace(/\D/g,''))||0),0)+1;const w={id:'W'+String(n).padStart(3,'0'),name,mobile,status:'Available',lat:null,lng:null,lastLocation:null};d.workers.push(w);writeDB(d);return send(res,200,w)}
if(u.pathname==='/api/worker'&&req.method==='DELETE'){const id=String(u.searchParams.get('workerId')||'').toUpperCase();if(!id)return send(res,400,{error:'Worker ID required'});const assigned=d.complaints.some(c=>c.workerId===id&&c.status!=='Resolved');if(assigned)return send(res,400,{error:'Technician has active complaints. Reassign them first.'});d.workers=d.workers.filter(w=>w.id!==id);writeDB(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/worker/status'&&req.method==='POST'){const x=await body(req),w=d.workers.find(a=>a.id===String(x.workerId||'').toUpperCase());if(!w)return send(res,404,{error:'Worker not found'});w.status=String(x.status)==='Busy'?'Busy':'Available';w.statusUpdatedAt=new Date().toISOString();writeDB(d);return send(res,200,w)}
	if(u.pathname==='/api/worker/location'&&req.method==='POST'){const x=await body(req),w=d.workers.find(a=>a.id===String(x.workerId||'').toUpperCase());if(!w)return send(res,404,{error:'Worker not found'});w.lat=Number(x.lat);w.lng=Number(x.lng);w.lastLocation=new Date().toISOString();writeDB(d);return send(res,200,w)}
if(u.pathname==='/api/complaint'&&req.method==='DELETE'){
 const id=String(u.searchParams.get('id')||'').trim();
 const idx=d.complaints.findIndex(c=>c.id===id);
 if(idx<0)return send(res,404,{error:'Complaint not found'});
 d.complaints.splice(idx,1);
 writeDB(d);
 return send(res,200,{ok:true});
}
if(u.pathname==='/api/complaint'&&req.method==='GET'){const id=(u.searchParams.get('customerId')||'').trim().toUpperCase();return send(res,200,id?d.complaints.filter(c=>c.customerId===id).slice().reverse():d.complaints.slice().reverse())}
if(u.pathname==='/api/complaint'&&req.method==='POST'){const x=await body(req),c={id:'CMP'+Date.now(),customerId:String(x.customerId||'').toUpperCase(),type:String(x.type||'Other'),message:String(x.message||''),status:'Open',priority:String(x.priority||'Normal')==='Urgent'?'Urgent':'Normal',workerId:null,workerName:null,customerLat:x.lat==null?null:Number(x.lat),customerLng:x.lng==null?null:Number(x.lng),createdAt:new Date().toISOString(),date:new Date().toLocaleString('en-IN'),technicianDone:false,customerConfirmed:false};d.complaints.push(c);const cu=d.customers.find(a=>a.id===c.customerId);addNotification(d,'ADMIN','🚨 New Complaint',`${c.customerId} ${cu?.name||''} submitted: ${c.type} — ${c.message}`);writeDB(d);return send(res,200,c)}
if(u.pathname==='/api/complaints'&&req.method==='GET'){return send(res,200,d.complaints.slice().reverse().map(c=>{const cu=d.customers.find(x=>x.id===c.customerId);return Object.assign({},c,{customerName:cu?.name||c.customerId,customerAddress:cu?.address||''})}))}
if(u.pathname==='/api/complaint/location'&&req.method==='POST'){const x=await body(req),c=d.complaints.find(a=>a.id===x.id);if(!c)return send(res,404,{error:'Complaint not found'});if(c.customerId!==String(x.customerId||'').toUpperCase())return send(res,403,{error:'Not your complaint'});c.customerLat=x.lat==null?null:Number(x.lat);c.customerLng=x.lng==null?null:Number(x.lng);c.locationUpdatedAt=new Date().toISOString();writeDB(d);return send(res,200,c)}
if(u.pathname==='/api/complaint/assign'&&req.method==='POST'){const x=await body(req),c=d.complaints.find(a=>a.id===x.id),w=d.workers.find(a=>a.id===String(x.workerId||'').toUpperCase());if(!c||!w)return send(res,404,{error:'Complaint or worker not found'});if(w.status==='Busy'&&c.workerId!==w.id)return send(res,400,{error:'Technician is Busy. Select an Available technician.'});c.workerId=w.id;c.workerName=w.name;c.status='Assigned';c.assignedAt=new Date().toISOString();w.status='Busy';addNotification(d,c.customerId,'👨‍🔧 Technician Assigned',`${w.name} has been assigned to your complaint. You will receive updates here.`);writeDB(d);return send(res,200,c)}
if(u.pathname==='/api/complaint/status'&&req.method==='POST'){const x=await body(req),c=d.complaints.find(a=>a.id===x.id);if(!c)return send(res,404,{error:'Complaint not found'});if(x.workerId&&c.workerId!==String(x.workerId).toUpperCase())return send(res,403,{error:'Not assigned to this worker'});const next=String(x.status||c.status);c.status=next;if(next==='On the Way'){c.onTheWayAt=new Date().toISOString();addNotification(d,c.customerId,'🚗 Technician On The Way',`${c.workerName||'Technician'} is on the way to you. Check the complaint screen for live distance/ETA when location is available.`)}if(next==='Working'){c.workStartedAt=new Date().toISOString();addNotification(d,c.customerId,'🔧 Technician Reached',`${c.workerName||'Technician'} has started working on your complaint.`)}if(next==='Technician Completed'){c.technicianDone=true;c.technicianDoneAt=new Date().toISOString();c.status=c.customerConfirmed?'Resolved':'Customer Confirmation Pending';addNotification(d,c.customerId,'✅ Work Completed',`${c.workerName||'Technician'} marked the work completed. Please open Support and confirm PROBLEM SOLVED.`)}if(c.status==='Resolved'){const w=d.workers.find(a=>a.id===c.workerId);if(w)w.status='Available';addNotification(d,c.customerId,'🟢 Complaint Resolved','Your complaint has been confirmed as resolved.');}writeDB(d);return send(res,200,c)}
if(u.pathname==='/api/complaint/customer-confirm'&&req.method==='POST'){const x=await body(req),c=d.complaints.find(a=>a.id===x.id);if(!c)return send(res,404,{error:'Complaint not found'});if(c.customerId!==String(x.customerId||'').toUpperCase())return send(res,403,{error:'Not your complaint'});c.customerConfirmed=true;c.customerConfirmedAt=new Date().toISOString();c.status=c.technicianDone?'Resolved':'Technician Confirmation Pending';if(c.status==='Resolved'){const w=d.workers.find(a=>a.id===c.workerId);if(w)w.status='Available';addNotification(d,c.customerId,'🟢 Complaint Resolved','Thank you. Both customer and technician have confirmed the complaint is resolved.')}else addNotification(d,c.customerId,'👍 Confirmation Received','Your confirmation was received. Waiting for technician confirmation.');writeDB(d);return send(res,200,c)}
if(u.pathname==='/api/complaint/update'&&req.method==='POST'){const x=await body(req),c=d.complaints.find(a=>a.id===x.id);if(!c)return send(res,404,{error:'Complaint not found'});if(x.priority)c.priority=String(x.priority)==='Urgent'?'Urgent':'Normal';if(x.expectedVisitAt!==undefined)c.expectedVisitAt=String(x.expectedVisitAt||'').trim();if(x.note!==undefined)c.workNote=String(x.note||'').trim();if(x.materials!==undefined)c.materials=String(x.materials||'').trim();if(x.beforePhoto)c.beforePhoto=String(x.beforePhoto);if(x.afterPhoto)c.afterPhoto=String(x.afterPhoto);c.updatedAt=new Date().toISOString();writeDB(d);return send(res,200,c)}
	if(u.pathname==='/api/complaint/resolve'&&req.method==='POST'){const x=await body(req),c=d.complaints.find(a=>a.id===x.id);if(!c)return send(res,404,{error:'Complaint not found'});c.technicianDone=true;c.customerConfirmed=true;c.status='Resolved';c.resolvedAt=new Date().toISOString();writeDB(d);return send(res,200,c)}
if(u.pathname==='/api/upgrades'&&req.method==='GET'){const id=(u.searchParams.get('customerId')||'').trim().toUpperCase();return send(res,200,d.upgrades.filter(x=>!id||x.customerId===id).slice().reverse())}
if(u.pathname==='/api/upgrade'&&req.method==='POST'){const x=await body(req),id=String(x.customerId||'').trim().toUpperCase(),c=d.customers.find(a=>a.id===id),p=d.plans.find(a=>a.name===String(x.plan||'').trim());if(!c||!p)return send(res,400,{error:'Customer or plan not found'});if(c.plan===p.name)return send(res,400,{error:'Customer is already on this plan'});const existing=d.upgrades.find(a=>a.customerId===id&&a.status==='Pending');if(existing)return send(res,400,{error:'A pending upgrade request already exists'});const q={id:'UP'+Date.now(),customerId:id,customerName:c.name,currentPlan:c.plan,currentPrice:Number(c.price||0),requestedPlan:p.name,requestedPrice:Number(p.price),status:'Pending',createdAt:new Date().toISOString()};d.upgrades.push(q);writeDB(d);return send(res,200,q)}
if(u.pathname==='/api/upgrades'&&req.method==='GET')return send(res,200,d.upgrades.filter(x=>x.status!=='Rejected').slice().reverse())
if(u.pathname==='/api/upgrade/approve'&&req.method==='POST'){const x=await body(req),q=d.upgrades.find(a=>a.id===x.id);if(!q)return send(res,404,{error:'Upgrade request not found'});if(q.status!=='Pending')return send(res,400,{error:'Request already processed'});const c=d.customers.find(a=>a.id===q.customerId);const p=d.plans.find(a=>a.name===q.requestedPlan);if(!c||!p)return send(res,400,{error:'Customer or plan not found'});c.plan=p.name;c.price=Number(p.price);q.status='Approved';q.approvedAt=new Date().toISOString();writeDB(d);return send(res,200,q)}
if(u.pathname==='/api/upgrade/reject'&&req.method==='POST'){const x=await body(req),q=d.upgrades.find(a=>a.id===x.id);if(!q)return send(res,404,{error:'Upgrade request not found'});if(q.status!=='Pending')return send(res,400,{error:'Request already processed'});q.status='Rejected';q.rejectedAt=new Date().toISOString();writeDB(d);return send(res,200,q)}
if(u.pathname==='/api/plans'&&req.method==='GET')return send(res,200,d.plans);
if(u.pathname==='/api/plan'&&req.method==='DELETE'){const name=String(u.searchParams.get('name')||'').trim();if(!name)return send(res,400,{error:'Plan name required'});if(d.customers.some(c=>c.plan===name))return send(res,400,{error:'Plan is assigned to customers. Change their plans first.'});d.plans=d.plans.filter(p=>p.name!==name);writeDB(d);return send(res,200,{ok:true})}
if(u.pathname==='/api/plan'&&req.method==='POST'){const x=await body(req);const p={name:String(x.name||'').trim(),price:Number(x.price||0)};if(!p.name||!p.price)return send(res,400,{error:'Plan name and price required'});d.plans.push(p);writeDB(d);return send(res,200,p)}
let file=u.pathname==='/'?'customer.html':u.pathname==='/admin'?'admin.html':u.pathname==='/worker'?'worker.html':null;if(!file)return send(res,404,{error:'Not found'});return send(res,200,fs.readFileSync(path.join(__dirname,'public',file),'utf8'),'text/html; charset=utf-8');
}catch(e){console.error(e);return send(res,500,{error:e.message})}});server.listen(PORT,'0.0.0.0',()=>console.log(`Rao Brothers app server running on port ${PORT}`));
